user_token: вставьте_ваш_токен_вместо_этой_строки

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
bot:
  token: group_token
  group_id: 1


